---
apiVersion: v1
kind: Service
metadata:
  name: my-exporter
  namespace: openshift-paulc
  annotations:
    prometheus.io/port: "9696"
    prometheus.io/scheme: "http"
    prometheus.io/scrape: "true"
  labels:
    app: my-exporter
spec:
  type: ClusterIP
  ports:
  - port: 9696
    targetPort: 9696
    name: my-exporter-port
    protocol: TCP
  selector:
    app: my-exporter