---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-exporter
  namespace: openshift-paulc
spec:
  selector:
    matchLabels:
      app: my-exporter
  endpoints:
  - port: my-exporter-port
    path: /metrics
    interval: 5s
    scheme: http

